import Image from "next/image";
import { Inter } from "next/font/google";
import Navbar from "@/components/layouts/Navbar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Hallo saya dari bizzagi</h1>
    </div>
  );
}
